module.exports = {
  // ASYNC.
  // -------------------------------------------------------------------------->
  ACCOUNT_REQUEST: 'ACCOUNT_REQUEST',
  ACCOUNT_SUCCESS: 'ACCOUNT_SUCCESS',
  ACCOUNT_FAILURE: 'ACCOUNT_FAILURE',
  // -------------------------------------------------------------------------->
  ACCOUNTS_REQUEST: 'ACCOUNTS_REQUEST',
  ACCOUNTS_SUCCESS: 'ACCOUNTS_SUCCESS',
  ACCOUNTS_FAILURE: 'ACCOUNTS_FAILURE',
  // -------------------------------------------------------------------------->
  LOGS_REQUEST: 'LOGS_REQUEST',
  LOGS_SUCCESS: 'LOGS_SUCCESS',
  LOGS_FAILURE: 'LOGS_FAILURE',
  // -------------------------------------------------------------------------->
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  // -------------------------------------------------------------------------->
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',
  // -------------------------------------------------------------------------->
  SIGNUP_REQUEST: 'SIGNUP_REQUEST',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',
  // -------------------------------------------------------------------------->
  REGISTER_INTEREST_REQUEST: 'REGISTER_INTEREST_REQUEST',
  REGISTER_INTEREST_SUCCESS: 'REGISTER_INTEREST_SUCCESS',
  REGISTER_INTEREST_FAILURE: 'REGISTER_INTEREST_FAILURE',
  // -------------------------------------------------------------------------->
  // SYNC.
  // -------------------------------------------------------------------------->
  NEXT_PATH_NAME: 'NEXT_PATH_NAME',
  SET_ROUTER: 'SET_ROUTER'
};
